### ISSUE TITLE
TIKZ code as result

### ISSUE THREAD

**Issue by MBoegers** [BITPlan/diagrams#9]
Using [TIKZ](https://github.com/pgf-tikz/pgf) is the common way to draw pictures/diagrams with latex.
An output option would be very helpful.
Below is an example of an UML-Class diagram using the [tikz-uml](https://perso.ensta-paris.fr/~kielbasi/tikzuml/var/files/doc/tikzumlmanual.pdf) package, see [overleaf example](https://www.overleaf.com/latex/templates/uml-diagrams-with-tikz-uml/ftfzzpmwnjqw) as well.

```latex
\begin{tikzpicture}
  \begin{umlpackage}{EquipmentProfile}
    \umlclass[]{Terminal}{conductedTo : ACLineSegment\\limit: Limit}{}
    \umlclass[x=-5, y=-3]{Limit}{value : double}{}
    \umlclass[x=+5, y=-3]{ACLineSegment}{}{}
    \umlclass[y=-5]{IdentifiedObject}{name : string\\mrid : IRI}{}
    
    \umlinherit[geometry=|-]{ACLineSegment}{IdentifiedObject}
    \umlinherit[geometry=|-]{Limit}{IdentifiedObject}
    \umlinherit[geometry=-|]{Terminal}{IdentifiedObject}
    
    \umlunicompo[mult=0..2, pos2=0.5]{Terminal}{ACLineSegment}
    \umlunicompo[mult=1]{Terminal}{Limit}
  \end{umlpackage}
\end{tikzpicture}
```
Renders to:
![grafik](https://user-images.githubusercontent.com/7557397/94411719-2e09d900-0179-11eb-8c62-945db2a798e3.png)

**Comment by WolfgangFahl** [comment]
Would direct latex code as in https://plantuml.com/de/latex also be acceptable?

**Comment by WolfgangFahl** [comment]
see https://de.overleaf.com/read/qrxwdbpwjgkb for how the diagrams service can already help with Latex/Overleav
